Updating Readme to add a new Clusterrole
openshift/csi-driver-shared-resource pull request #190
Opened 2024-06-25 12:59 UTC by ayushsatyam146

Updating the documentation to include the step
granting RBAC "get", "list", and "watch"
access to the resource being shared to the CSI
Driver's service account via a Cluserrole.
Adding the steps to create the Clusterrole
which will be created by the resource owner.

2024-06-27 08:06 UTC, sayan-biswas commented
/cc @adambkaplan

2024-08-06 08:00 UTC, apoorvajagtap requested changes

2024-08-06 08:00 UTC, apoorvajagtap commented on README.md
> +    ```
We'll need an additional step to add the clusterrole to the `csi-driver-shared-resource`.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-builds-shared-resource-secret-configmap-share-watch-sar-create
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-builds-shared-resource-secret-configmap-share-watch-sar-create
subjects:
- kind: ServiceAccount
  name: csi-driver-shared-resource
  namespace: openshift-builds
```

2024-08-06 11:43 UTC, apoorvajagtap approved these changes

2024-08-07 10:35 UTC, ramessesii2 commented
/retest

2024-08-07 11:14 UTC, sayan-biswas commented
There's no code change here, and having some issues with konflux ci. 
Hence merging this.

2024-08-07 11:14 UTC, merged

2024-08-07 11:15 UTC, sayan-biswas commented
/approved