OCPBUGS-37141: Bump go version from 1.21 to 1.21.11
openshift/csi-driver-shared-resource pull request #220
Opened 2024-10-22 09:46 UTC by ayushsatyam146

Bump go version from 1.21 to 1.21.11 to fix [CVE-2024-24789](https://issues.redhat.com/issues/?jql=labels+%3D+CVE-2024-24789)

2024-10-23 12:24 UTC, adambkaplan requested changes
You will also need to update the golang version we use in the Konflux `Dockerfile`. See https://github.com/openshift/csi-driver-shared-resource/blob/master/.konflux/cdsr/Dockerfile#L1

2024-10-24 13:04 UTC, adambkaplan requested changes

2024-10-24 13:04 UTC, adambkaplan commented on .konflux/cdsr/Dockerfile
The Dockerfile for the webhook also needs to be updated (same issue as this one).

2024-10-25 21:46 UTC, closed without merging

2024-10-25 21:48 UTC, sayan-biswas commented
This is relevant to CSI driver released with OCP. And Docker file for that is under the root. Which already has the golang version updated. 
Konflux related changes are in builds-1.1 branch and is already updated to golang 1.21
Hence closing this PR.