BUILD-401: Add entitled bld example
openshift/csi-driver-shared-resource pull request #83
Opened 2022-01-11 19:09 UTC by gabemontero

/assign @coreydaley 
for general code review
/assign @jitendar-singh 
/assign @prietyc123 
for qe approved label - the doc here are my instructions on how to manually verify this scenario
/assign @rolfedh 
for docs approved label - this doc here is my input for the "connecting of the dots" item that @siamaksade opened against you for explaining how to use insights operator, shared resource operator, and openshift builds to do entitled buidls *WITHOUT* copying the subscription credentials into a secret in the same namespace as the build config, as we currently document as the way to do entitlements with openshift builds in https://docs.openshift.com/container-platform/4.9/cicd/builds/running-entitled-builds.html

@openshift/openshift-team-build-api-maintainers FYI

As I understood @adambkaplan during planning today, the next story where we actually create the blog post is where we "officially" engage with PX and get their comfort level / reqs on all this, so 

/label px-approved

2022-01-11 19:09 UTC, gabemontero commented
/approve

2022-01-11 20:04 UTC, adambkaplan requested changes

2022-01-11 20:04 UTC, adambkaplan commented on docs/simple-example.md
> +So both OpenShift Shared Resources and OpenShift Insights Operator are only available on Tech Preview clusters.
Starting a sentence with "So" is very informal, and isn't necessary. In addition, the Insights Operator itself is available on all clusters - only the "download Simple Content Accesss cert" is tech preview.

```suggestion
Tech Preview must be enabled on your OCP cluster to use the Shared Resources CSI Driver and to sync the Simple Content Access certificate of your Red Hat account.
```

2022-01-11 20:04 UTC, adambkaplan commented on docs/simple-example.md
> +## BuildConfig example
This section is sufficiently complex that I would put it in a separate document.

2022-01-11 20:05 UTC, adambkaplan commented
@gabemontero a note regarding PR descriptions - both the PR title and description are used to generate customer-facing changelogs. Therefore, please update the PR title and description so that it is readable to an end-user.

Team member mentions should be placed in separate comments.

2022-01-12 13:13 UTC, coreydaley requested changes

2022-01-12 13:13 UTC, coreydaley commented on docs/simple-example.md
> +Red Hat subscription that entitles you to install Red Hat RPMs.  With a referenced to this `SharedSecret`, the `BuildConfig`
```suggestion
Red Hat subscription that entitles you to install Red Hat RPMs.  With a reference to this `SharedSecret`, the `BuildConfig`
```

2022-01-12 13:13 UTC, coreydaley commented on docs/simple-example.md
> +is able to use your subscription information to installed entitled RPMs when building an image.  Separate `Role` and
```suggestion
is able to use your subscription information to installe entitled RPMs when building an image.  Separate `Role` and 
```

2022-01-12 13:13 UTC, coreydaley commented on docs/simple-example.md
> +`RoleBinding` objects are defined for the `BuildConfig` and its use of the `SharedSecret`
```suggestion
`RoleBinding` objects are defined for the `BuildConfig` and its use of the `SharedSecret`.
```

2022-01-12 13:13 UTC, coreydaley commented on docs/simple-example.md
> +and what as Red Hat entitled content via your subscription is installed during the running of the Docker Strategy build.
```suggestion
and watch as Red Hat entitled content via your subscription is installed during the running of the Docker Strategy build.
```

2022-01-12 13:30 UTC, gabemontero commented
updates made @adambkaplan PTAL thanks

2022-01-12 13:33 UTC, gabemontero commented
I'll have to do your suggested commits manually @coreydaley since I moved that content to a new file per @adambkaplan but I'll get that started soon thanks

2022-01-12 13:38 UTC, gabemontero commented
@adambkaplan hold a bit on reviewing for you comments ... @coreydaley 's comments made me realize I need to move some doc content from the old file to the new one

2022-01-12 14:34 UTC, gabemontero commented
ok @adambkaplan @coreydaley I think I have both your sets of comments reconciled and applied together ... PTAL when you get the chance - thanks

2022-01-12 15:28 UTC, gabemontero commented
bump @rolfedh 

for doc approve label ... the new markdowns serve as my input to you for https://issues.redhat.com/browse/RHDEVDOCS-3631

2022-01-12 15:31 UTC, gabemontero commented
bump @jitendar-singh @prietyc123 

for qe approve label

this pr provides the yaml and instructions for you to try entitled builds yourself as part of manual verification (along with an associated feature file in the `smoke` dir for https://issues.redhat.com/browse/BUILD-400

2022-01-12 15:32 UTC, gabemontero commented
@adambkaplan @jitendar-singh @prietyc123 how do you all want to handle the assignment of https://issues.redhat.com/browse/BUILD-400 ? ... it is currently unassigned

2022-01-12 15:32 UTC, gabemontero commented
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_csi-driver-shared-resource/83/pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver-disruptive/1481256911906017280 was an AWS fail

2022-01-12 19:09 UTC, rolfedh commented
/label docs-approved

2022-01-12 19:48 UTC, coreydaley commented on README.md
> +[here](docs/simple-example.md), and for the `BuildConfig` example are [here]().
missing link

2022-01-12 20:18 UTC, gabemontero commented
link added thanks @coreydaley 

ptal @coreydaley @adambkaplan

2022-01-12 21:45 UTC, gabemontero commented
aws flake on https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_csi-driver-shared-resource/83/pull-ci-openshift-csi-driver-shared-resource-master-e2e-aws-csi-driver-slow/1481360209472393216

/retest

2022-01-13 14:13 UTC, gabemontero commented
no more flakes - all tests are green

@adambkaplan @coreydaley PTAL

2022-01-14 15:24 UTC, gabemontero commented
@rolfedh - I've added a section to the google doc input into the new "Shared Resources" docs that is a starting point for its "connect the docs" piece ...i.e. connecting the dots between the doc articles around Shared Resources, Builds, and Insight Operator/Simple Content Access.

2022-01-18 16:19 UTC, coreydaley commented
/lgtm

2022-01-18 18:05 UTC, gabemontero commented
ok @coreydaley rebase handled (it was simple, an existing file was renamed in this PR)

PTAL / retag for merge

2022-01-18 18:15 UTC, coreydaley commented
/lgtm

2022-01-20 20:25 UTC, adambkaplan commented
/assign @prietyc123 @jitendar-singh 

for qe approval.

2022-01-21 06:28 UTC, prietyc123 commented
/label qe-approved

2022-01-21 07:45 UTC, merged