add webhook main entrypoint and dockerfile
openshift/csi-driver-shared-resource pull request #92
Opened 2022-04-13 13:13 UTC by jkhelil

2022-04-18 12:24 UTC, gabemontero commented
/retitle BUILD-469: add webhook main entrypoint and dockerfile

2022-04-18 12:32 UTC, gabemontero commented
so yeah presumably we need https://github.com/openshift/release/pull/27887 to merge for the images job to start passing here with the moving of the Dockerfile locations

2022-04-19 14:10 UTC, jkhelil commented
/retest

2022-04-19 15:43 UTC, gabemontero commented on images/Dockerfile
> +COPY .. .
revert this change too

2022-04-19 15:52 UTC, gabemontero requested changes

2022-04-19 15:56 UTC, gabemontero commented on cmd/csidriver/main_test.go
> +	cfgFilePath := "../../test/config/config.yaml"
not sure why this is necessary ... but the e2e's should sort it out once we have fixed the image building stuff between here and the updated openshift/release PR

2022-04-19 15:59 UTC, jkhelil commented on images/Dockerfile.webhook
> +COPY --from=builder /go/src/github.com/openshift/csi-driver-shared-resource/_output/csi-driver-shared-resource /usr/bin/
done

2022-04-20 17:36 UTC, gabemontero requested changes
So @jkhelil I'll give you 2 choices based on the guidance we got from Ben in your openshift/release PR

1) just move the Dockerfiles out of the image sub directory back into the top level directory, and delete the images subdirectory

2) get what you were intending with 3 PRs
   a) this PR creates Dockerfiles in both the top level dir and the images dir ... once https://github.com/openshift/release/pull/27951 we should get clean runs, we can merge this
   b) after this merges, you create a new openshift/release PR that points to the dockerfiles in the images subdir
   c) after b) merges, create a new PR here that deletes the dockerfiles in the top level dir

I'll let you decide what you want to do

2022-04-20 17:51 UTC, jkhelil commented
> So @jkhelil I'll give you 2 choices based on the guidance we got from Ben in your openshift/release PR
> 
> 1. just move the Dockerfiles out of the image sub directory back into the top level directory, and delete the images subdirectory
> 2. get what you were intending with 3 PRs
>    a) this PR creates Dockerfiles in both the top level dir and the images dir ... once [openshift/release#27951](https://github.com/openshift/release/pull/27951) we should get clean runs, we can merge this
>    b) after this merges, you create a new openshift/release PR that points to the dockerfiles in the images subdir
>    c) after b) merges, create a new PR here that deletes the dockerfiles in the top level dir
> 
> I'll let you decide what you want to do

I took the first option @gabemontero , I removed the images directory and just let it the dockerfiles in the top level dir

2022-04-20 17:59 UTC, gabemontero approved these changes
just to make sure, I checked out this PR and was able to make build-*-image all 3 images, as well as run `make test-e2e` and see the main_test.go change function correctly

/approve
/lgtm

2022-04-20 18:03 UTC, gabemontero commented
/label px-approved

no end user impact

2022-04-20 18:05 UTC, gabemontero commented
/label qe-approved

no qe impact yet, that will come with the real impl of the webhook

2022-04-20 18:05 UTC, gabemontero commented
/label docs-approved

no doc impact yet, that will come with the real impl of the webhook

2022-04-20 18:18 UTC, gabemontero commented
/lgtm cancel

missed something ... from the images job:

`error: error copying source path /go/src/github.com/openshift/csi-driver-shared-resource/images/. to .: exit status 1`

2022-04-20 18:20 UTC, gabemontero commented
sigh .... we need to just undo the context dir stuff in https://github.com/openshift/release/pull/27887 before this will build clean @jkhelil

2022-04-20 18:31 UTC, gabemontero commented
ok have https://github.com/openshift/release/pull/27998 ^^ up

2022-04-20 21:28 UTC, gabemontero commented
/retest

2022-04-20 21:38 UTC, gabemontero commented
ok we have clean images 

/lgtm

2022-04-20 22:51 UTC, merged